### ISSUE TITLE
FontString:SetFont()

### ISSUE THREAD

**Issue by Hollicsh** [lowlee/MikScrollingBattleText#2]
50x FontString:SetFont(): Arguments: ("font", fontHeight [, flags])
[string "=[C]"]: in function `SetFont'
[string "@Interface/AddOns/MikScrollingBattleText/MSBTAnimations.lua"]:302: in function <...ace/AddOns/MikScrollingBattleText/MSBTAnimations.lua:241>
[string "@Interface/AddOns/MikScrollingBattleText/MSBTAnimations.lua"]:414: in function <...ace/AddOns/MikScrollingBattleText/MSBTAnimations.lua:360>
[string "@Interface/AddOns/MikScrollingBattleText/MSBTCooldowns.lua"]:273: in function <...face/AddOns/MikScrollingBattleText/MSBTCooldowns.lua:220>

Locals:
(*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = 22
(*temporary) = ""

**Comment by lowlee** [comment]
What is the issue you are having?

What is the expected behavior?

What actually happened?

Suggested Solution/Workaround

**Comment by Hollicsh** [comment]
I just entered the game. This error appeared immediately. I have no idea where she could come from.

**Comment by lowlee** [comment]
I can't replicate the issue.

Fresh wow install and just MSBT installed works fine.

Could you try backing up your MSBT saved variables and deleting them and then restarting the game.

(Backup WoW/_retail_/WTF/Account/[AccountName]/SavedVariables/MikScrollingBattleText.lua - to a new location and then delete the original file)

If you need to restore it just copy your backup into the WoW/_retail_/WTF/Account/[AccountName]/SavedVariables directory

**Comment by Hollicsh** [comment]
I completely uninstalled the addon, deleted all folders and reinstalled. Now everything works fine !

Thank u !
